name: Build and Test

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout pcre
        uses: actions/checkout@v2
        with:
          path: pcre

      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Run tests
        run: v test pcre/

      - name: Compile lib
        run: v -shared pcre/

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout pcre
        uses: actions/checkout@v2
        with:
          path: pcre

      - name: Build V
        run: |
          make
          ./v symlink

      - name: Run tests
        run: v test pcre/

      - name: Compile lib
        run: v -shared pcre/

  windows:
    runs-on: windows-latest
    env:
      VFLAGS: -cc gcc
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout pcre
        uses: actions/checkout@v2
        with:
          path: pcre

      - name: Build V
        run: |
          .\make.bat -gcc

      - name: Run tests
        run: .\v.exe test pcre\

      - name: Compile lib
        run: .\v.exe -shared pcre\
